export const WALL_PIXEL_WIDTH = 2048;
export const WALL_PIXEL_HEIGHT = 1024;
export const WORLD_WALL_WIDTH = 16;
export const WORLD_WALL_HEIGHT = WORLD_WALL_WIDTH * (WALL_PIXEL_HEIGHT / WALL_PIXEL_WIDTH);
